### ISSUE TITLE
Cloning to plugins folder results in File Not Found +  error 500

### ISSUE THREAD

**Issue by ghost** [hermannmarkus/Pico-FeedMaker#1]
Hi, I seem to be unable to use Pico-FeedMaker. If I clone it into my Pico plugins directory, even without enabling it in config.yml, I get the following error coming up:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to load plugin 'Pico-FeedMaker' from 'Pico-FeedMaker/Pico-FeedMaker.php': File not found in /var/www/site.com/pico/vendor/picocms/pico/lib/Pico.php:639\nStack trace:\n#0 /var/www/site.com/pico/vendor/picocms/pico/lib/Pico.php(520): Pico->loadLocalPlugins(Array)\n#1 /var/www/site.com/pico/vendor/picocms/pico/lib/Pico.php(401): Pico->loadPlugins()\n#2 /var/www/site.com/pico/index.php(33): Pico->run()\n#3 {main}\n  thrown in /var/www/site.com/pico/vendor/picocms/pico/lib/Pico.php on line 639\n'

**Comment by hermannmarkus** [comment]
Hi,

how exactly did you clone the repo?

As mentioned in the readme you should clone via: `git clone https://github.com/hermannmarkus/Pico-FeedMaker.git FeedMaker`

The `FeedMaker` at the end is important, because it will clone into the folder FeedMaker. When you clone without it, git will clone into the folder `Pico-FeedMaker`. From your error message it seems like this happened.

The problem is that pico will look for the plugin class dependent of the folder name. So when you clone into `FeedMaker` it will look for the class `FeedMaker`. So, when you cloned into `Pico-FeedMaker` Pico will look for another class.

Just renaming the folder to `FeedMaker` should fix the error.
